### ISSUE TITLE
Release 1.14.18 Failing to Build

### ISSUE THREAD

**Issue by gmlander** [pymupdf/PyMuPDF#325]
Attempting to rebuild a container this morning that was working with 1.14.17 failed with the latest release. Trace is below.

> Running setup.py install for pymupdf: finished with status 'error'
>     Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mzpb_6aj/pymupdf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vu2q7kyt-record/install-record.txt --single-version-externally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-3.6
>     creating build/lib.linux-x86_64-3.6/fitz
>     copying fitz/__init__.py -> build/lib.linux-x86_64-3.6/fitz
>     copying fitz/fitz.py -> build/lib.linux-x86_64-3.6/fitz
>     copying fitz/utils.py -> build/lib.linux-x86_64-3.6/fitz
>     running build_ext
>     building 'fitz._fitz' extension
>     creating build/temp.linux-x86_64-3.6
>     creating build/temp.linux-x86_64-3.6/fitz
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/mupdf -I/usr/local/include/mupdf -I/usr/local/thirdparty/zlib -I/usr/include/python3.6m -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.6/fitz/fitz_wrap.o
>     fitz/fitz_wrap.c:2732:10: fatal error: fitz.h: No such file or directory
>      #include <fitz.h>
>               ^~~~~~~~
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     ----------------------------------------
> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mzpb_6aj/pymupdf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-vu2q7kyt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-mzpb_6aj/pymupdf/

**Comment by JorjMcKie** [comment]
yes, I have screwed that version somehow.
Please let me straighten it out with a new version

**Comment by vanderGoes** [comment]
I'm having a similar issue. On pip install in a Jupyter notebook: `Command "/mnt/anaconda2/envs/py34/bin/python -u -c "import setuptools, tokenize;__file__='/mnt/tmp/pip-build-7630yhq5/PyMuPDF/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ptjfjwvs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /mnt/tmp/pip-build-7630yhq5/PyMuPDF/`

Had to revert back to 1.14.17

**Comment by JorjMcKie** [comment]
I will upload a new version today

**Comment by JorjMcKie** [comment]
new v1.14.19 now on PyPI

**Comment by JorjMcKie** [comment]
Accidentally edited ``PKG-INFO`` with an editor option that removes spaces at line ends. This created lines only containing ``\n`` in the middle of the long description field for some wheels, which then PyPI rejected ... **sigh**

**Comment by JorjMcKie** [comment]
close this issue?
