### ISSUE TITLE
AttributeError: 'Page' object has no attribute 'MediaBox' (1.20.0)

### ISSUE THREAD

**Issue by mahboobmm** [pymupdf/PyMuPDF#1758]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)
I am facing the following error when I re-run my code on the latest version of the package. 
```AttributeError: 'Page' object has no attribute 'MediaBox'```

## To Reproduce (mandatory)
1. Ensure you have version 1.20.0
2. Run the following code

    ```
     doc = fitz.open(file_name)

     for page_nr, page in enumerate(doc):
         pdf_w, pdf_h = page.MediaBox[2:]

## Expected behavior (optional)
The same code works fine on version 1.19.6

## Your configuration (mandatory)
 - Mac OS Monterey 12.3.1
 - Python 3.8.5
 - PyMuPDF 1.20.0, installed using pip

For example, the output of `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).

## Additional context (optional)
Add any other context about the problem here.

**Comment by JorjMcKie** [comment]
> The same code works fine on version 1.19.6

Maybe, but so what?
The documentation says `Page.mediabox`.

**Comment by JorjMcKie** [comment]
From the documentation you could also learn about a major re-naming - away from CamelCase to lower case / snake_case.
```
>>> import fitz
>>> help(fitz.Page.MediaBox)
Help on property:

    *** Deprecated and removed after v1.19 - use 'mediabox'. ***
    The MediaBox.

>>>
```

**Comment by JorjMcKie** [comment]
If you refuse to change your code (although announced to happen since 1.18.x more than a year ago), you can execute `fitz.restore_aliases()` after the import.
This will reactivate the old names.

**Comment by JorjMcKie** [comment]
Ok, I understand.
Welcome on board then!
