### ISSUE TITLE
Error with include ft2build.h because Pypi doesn't have an actual source for 1.18.8

### ISSUE THREAD

**Issue by frost-nzcr4** [pymupdf/PyMuPDF#894]
## Describe the bug (mandatory)
When PyMuPDF installled from source on Pypi it gets PyMuPDF-1.18.8.tar.gz from https://pypi.org/project/PyMuPDF/#files. Possibly there is an old setup.py that not contains latest changes for including freetype from /usr/include/freetype2 (commit d3c90a07e2f4eff64b18954e36efa45c05d89818).

## To Reproduce (mandatory)
Run `pip install pymupdf==1.18.8`

## Expected behavior (optional)
Source should contain latest setup.py with bugfixes.

## Your configuration (mandatory)
 - Ubuntu 20.04.2 LTS
 - Python 3.8.5, x64
 - PyMuPDF 1.18.8, **generated**.

## Additional context (optional)

Look at old `-Imupdf/thirdparty/freetype/include` in building error log:
```
 x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/mupdf -I/usr/local/include/mupdf -Imupdf/thirdparty/freetype/include -I/home/someuser/.venv/someenv/include -I/usr/include/python3.8 -c fitz/fitz_wrap.c -o build/temp.linux-x86_64-3.8/fitz/fitz_wrap.o
  fitz/fitz_wrap.c:2771:10: fatal error: ft2build.h: No such file or directory
```

**Comment by JorjMcKie** [comment]
This is what is contained in the 1.18.8 source for Linux types:
![grafik](https://user-images.githubusercontent.com/8290722/107672029-d755f500-6c6a-11eb-9557-b7ed222c7955.png)
And this is the same part in 1.18.7:
![grafik](https://user-images.githubusercontent.com/8290722/107672287-1a17cd00-6c6b-11eb-86bf-8598ff6b56be.png)

The two setup.py are identical and also coincide with the one used for generating the OSX & Linux wheels.
So you see me a bit puzzled ...

**Comment by frost-nzcr4** [comment]
I've just re-check and found that an outdated pip 18.1, when upgraded it to 21.0.1 it downloads PyMuPDF-1.18.8-cp38-cp38-manylinux2010_x86_64.whl and it will successfully installed.

But still setup.py from https://files.pythonhosted.org/packages/26/6c/34098cd963418e5122abd70f8d116300203aaeab086cc9c6bdaf1b39cbd0/PyMuPDF-1.18.8.tar.gz provided on [Pypi page](https://pypi.org/project/PyMuPDF/#files)
differs with source https://github.com/pymupdf/PyMuPDF/archive/1.18.8.tar.gz provided on [Github page](https://github.com/pymupdf/PyMuPDF/releases)

![PyMuPDF](https://user-images.githubusercontent.com/468395/107677483-5f5bef00-6cab-11eb-8807-3ca994e45173.png)

**Comment by JorjMcKie** [comment]
Ok, good.
But this discussion is futile anyway, because in case of an installation from sources it is always solely your responsibility to ensure correct pointers to the folders of the MuPDF installation - as pointed out on the home page.
All I can do is putting values in, that I deem probable to fit.
There always remain a fat chance that a previously / independently installed MuPDF is found somewhere else than one installed for PyMuPDF's purposes ... not to talk about the zillion different Linux flavours, etc.
