### ISSUE TITLE
getPixmap() call fails in version 1.18.9 

### ISSUE THREAD

**Issue by abarker** [pymupdf/PyMuPDF#941]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

getPixmap() call fails in version 1.18.9 but works in 1.18.8

## To Reproduce (mandatory)

```python
import sys, fitz
print("fitz version:", fitz.VersionBind)

document = fitz.open(sys.argv[1])
page_display_list = document[0].getDisplayList()
pixmap = page_display_list.getPixmap()

document.close()
```

This code works with version 1.18.8 but running with 1.18.9 installed
gives the following error:

```
fitz version: 1.18.9
Traceback (most recent call last):
  File "fail_pymupdf.py", line 13, in <module>
    pixmap = page_display_list.getPixmap()
AttributeError: 'DisplayList' object has no attribute 'getPixmap'
```

## Your configuration (mandatory)
 - Operating system, potentially version and bitness: Ubuntu 20.04, 64-bit, and I also got a bug report from a user running on Windows.
 - Python version, bitness: 3.8.5, 64-bit.
 - PyMuPDF version, installation method (**wheel** or **generated** from source): 1.18.9, wheel.

**Comment by JorjMcKie** [comment]
I forgot to include alias definitions for the old method names.
Will be corrected in next version.
If you use `DisplayList.get_pixmap()` and `DisplayList.get_textpage()` things should work.

**Comment by JorjMcKie** [comment]
fixed in just published v1.18.10
