### ISSUE TITLE
page.apply_redactions() exits without any error message

### ISSUE THREAD

**Issue by baleris** [pymupdf/PyMuPDF#1125]
output from this print: `print(sys.version, "\n", sys.platform, "\n", fitz.__doc__)` would be sufficient (for the first two bullets).
Message: '3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]'
Arguments: ('\n', 'win32', '\n', '\nPyMuPDF 1.17.5: Python bindings for the MuPDF 1.17.0 library.\nVersion date: 2020-08-06 06:31:06.\nBuilt for Python 3.6
 on win32 (32-bit).\n')
_________________________________________________

I have observed strange behavior while processing some pdf's, in phase of page.apply_redactions(). which just exits program execution without giving any error/warning message.

I have a pdf which contains some images, what i am trying to do here is- whenever i find images in a page i will replace that area with blank text(that is removing an image from a page). It works fine for most of the cases, however in some pages it just exits the process when i call page.apply_redactions(). 

here is the code sample:
imageList = doc.getPageImageList(page.number, full=True)
for img in imageList:
       rect = page.getImageBbox(img).round()
       page.addRedactAnnot(rect, text=" ")
page.apply_redactions()

i have tried to see the Object information as mentioned in the #464 couldn't see any difference, output is here:

 /Annots [ 336 0 R 585 0 R ]
  /Contents 11 0 R
  /CropBox [ 0 0 612 792 ]
  /Group <<
    /CS /DeviceRGB
    /S /Transparency
    /Type /Group
  >>
  /MediaBox [ 0 0 612 792 ]
  /Parent 2858 0 R
  /Resources <<
    /ExtGState <<
      /GS7 423 0 R
      /GS8 425 0 R
    >>
    /Font <<
      /F1 415 0 R
      /F2 422 0 R
      /F3 416 0 R
      /F4 413 0 R
      /F5 421 0 R
    >>
    /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
    /XObject <<
      /Image96 140 0 R
    >>
  >>
  /Rotate 0
  /StructParents 132
  /Tabs /S
  /Type /Page

doc.xrefObject(140)
 /BitsPerComponent 8
  /ColorSpace /DeviceRGB
  /Filter /FlateDecode
  /Height 281
  /Interpolate false
  /Length 1146
  /SMask 139 0 R
  /Subtype /Image
  /Type /XObject
  /Width 1375

Couldn't get why this process interrupts at apply_redactions() , I am really sorry i can't share the input pdf file here as it contains confidential data and not allowed to share.

Second part of this issue is, if i only take out that page(Which has this above issue) by cropping out specific page from a pdf document and tri to do same above operation on that page(remove images and then call apply_redactions()) it works fine without any error!.

Object information for this single page is here:
/Type /Page
  /Contents 11 0 R
  /Resources <<
    /ExtGState <<
      /GS7 33 0 R
    >>
    /Font <<
      /F1 51 0 R
      /F2 60 0 R
      /F3 64 0 R
      /F4 67 0 R
      /F5 36 0 R
    >>
    /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
    /XObject <<
      /Image45 14 0 R
    >>
  >>
  /MediaBox [ 0 0 612 792 ]
  /CropBox [ 0 0 612 792 ]
  /Rotate 0
  /Annots [ 12 0 R 15 0 R ]
  /Parent 34 0 R

doc.xrefObject(140)

 /BitsPerComponent 8
  /ColorSpace /DeviceRGB
  /Filter /FlateDecode
  /Height 281
  /Interpolate false
  /Length 1146
  /SMask 13 0 R
  /Subtype /Image
  /Type /XObject
  /Width 1375

Here only i see a difference in name of the image , that has been changed from "image96 140 0" to image45 14 0".

Please help me to understand what is causing an issue here while performing apply_redactions().

**Comment by JorjMcKie** [comment]
Looks like the Python interpreter crashed. This e.g. happens when storage areas are accessed illegally.
This is of course serious, but I cannot help you if I can't get a reproducing file.
You might consider sending it to my email if you cannot share it publicly here.

**Comment by baleris** [comment]
What would be the reason for accessing storage areas illegally ?

**Comment by JorjMcKie** [comment]
> What would be the reason for accessing storage areas illegally ?

Programming error - either in PyMuPDF or MuPDF.

I tried  your file on my machine and it worked with this script:
[apply.zip](https://github.com/pymupdf/PyMuPDF/files/6776181/apply.zip)

I saw you using v1.17.x: please do upgrade!

**Comment by baleris** [comment]
Yes, upgraded to 1.18.14 which is working here, however in next step of operation i am trying to close all instances/checking all instances of pdf by using "document.isClosed" . which was working in v1.17, but now in v1.18.14 its throwing an error - "'Document' object has no attribute 'isClosed' " is that been diminished in this version ? or do we have some alternatives here ?

**Comment by JorjMcKie** [comment]
has been renamed to `is_closed`.

**Comment by baleris** [comment]
in v1.18.14 'doc._delXmlMetadata()' is also been replaced with 'doc.del_xml_metadata()' ?

**Comment by JorjMcKie** [comment]
> in v1.18.14 'doc._delXmlMetadata()' is also been replaced with 'doc.del_xml_metadata()' ?

yes - in section [deprecated names](https://pymupdf.readthedocs.io/en/latest/znames.html) you find a (alomost) complete list.
The names starting underscored have not been official anyway.

There are a handful exceptions for renames not listed in the deprecated chapter: this only happens when the name was neither a method nor defined via `@property` decorator.

**Comment by baleris** [comment]
@JorjMcKie Thanks a lot.... Everything works fine now for my application.
