### ISSUE TITLE
1.22.0 error when using get_toc (AttributeError: 'SwigPyObject' object has no attribute)

### ISSUE THREAD

**Issue by SteveHawk** [pymupdf/PyMuPDF#2355]
_**Please provide all mandatory information!**_

## Describe the bug (mandatory)

When using Document.get_toc() function in PyMuPDF 1.22.0, `AttributeError: 'SwigPyObject' object has no attribute` was encountered after accessing a few PDFs.

The function works on 1.21.1, while crashing on 1.22.0.

## To Reproduce (mandatory)

Here's some simple code to reproduce:

```python
def create():
    # Create a test PDF with toc
    doc = fitz.Document()
    for _ in range(10):
        doc.new_page(doc.page_count)
    doc.set_toc([[1, "test", 1], [1, "test2", 5]])
    doc.save("test.pdf")


def read1():
    # Open many times
    for i in range(10):
        print(i)
        with fitz.open("test.pdf") as new_doc:
            new_doc.get_toc()


def read2():
    # Open once and read many times
    with fitz.open("test.pdf") as new_doc:
        for i in range(10):
            print(i)
            new_doc.get_toc()
```

After creating `test.pdf` using `create()`, invoking `read1()` and `read2()` gives out slightly different error messages:

`read1()`:

```text
swig/python detected a memory leak of type 'Outline *', no destructor found.
swig/python detected a memory leak of type 'Outline *', no destructor found.
Traceback (most recent call last):
  File "/data/test/recreate.py", line 30, in <module>
    read1()
  File "/data/test/recreate.py", line 18, in read1
    new_doc.get_toc()
  File "/home/steve/miniconda3/envs/test/lib/python3.11/site-packages/fitz/utils.py", line 1046, in get_toc
    doc.init_doc()
  File "/home/steve/miniconda3/envs/test/lib/python3.11/site-packages/fitz/fitz.py", line 5194, in init_doc
    self._outline.thisown = True
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SwigPyObject' object has no attribute 'thisown'
swig/python detected a memory leak of type 'Colorspace *', no destructor found.
swig/python detected a memory leak of type 'Colorspace *', no destructor found.
swig/python detected a memory leak of type 'Colorspace *', no destructor found.
```

`read2()`:

```text
Traceback (most recent call last):
  File "/data/test/recreate.py", line 31, in <module>
    read2()
  File "/data/test/recreate.py", line 26, in read2
    new_doc.get_toc()
  File "/home/steve/miniconda3/envs/test/lib/python3.11/site-packages/fitz/utils.py", line 1053, in get_toc
    toc = recurse(olItem, liste, lvl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/steve/miniconda3/envs/test/lib/python3.11/site-packages/fitz/utils.py", line 1015, in recurse
    if olItem.title:
       ^^^^^^^^^^^^
AttributeError: 'SwigPyObject' object has no attribute 'title'
swig/python detected a memory leak of type 'Outline *', no destructor found.
swig/python detected a memory leak of type 'Colorspace *', no destructor found.
swig/python detected a memory leak of type 'Colorspace *', no destructor found.
swig/python detected a memory leak of type 'Colorspace *', no destructor found.
swig/python detected a memory leak of type 'Outline *', no destructor found.
```

I tested the code on 1.21.1 and 1.22.0, 1.21.1 works just fine but 1.22.0 crashes as stated above.

## Expected behavior (optional)

Code should not crash.

## Your configuration (mandatory)

 - Ubuntu 20.04.6 LTS x86_64
 - Python 3.11.3 64-bit (packaged by conda-forge, GCC 11.3.0)
 - PyMuPDF 1.22.0, installed using wheel (PyMuPDF-1.22.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, Version date: 2023-04-14 00:00:01).

**Comment by julian-smith-artifex-com** [comment]
Fixed in PyMuPDF-1.22.1.
