### ISSUE TITLE
Could not build with mupdf-1.15.0

### ISSUE THREAD

**Issue by wenheping** [pymupdf/PyMuPDF#297]
Build error with the log:

    CC build/release/source/fitz/draw-mesh.o
    CC build/release/source/fitz/draw-paint.o
    CC build/release/source/fitz/draw-path.o
    CC build/release/source/fitz/draw-rasterize.o
    CC build/release/source/fitz/draw-scale-simple.o
    CC build/release/source/fitz/draw-unpack.o
    CC build/release/source/fitz/encode-basic.o
    CC build/release/source/fitz/encodings.o
    CC build/release/source/fitz/error.o
source/fitz/error.c:158:5: error: conflicting types for 'fz_push_try'
int fz_push_try(fz_context *ctx)
    ^
include/mupdf/fitz/context.h:56:13: note: previous declaration is here
fz_jmp_buf *fz_push_try(fz_context *ctx);
            ^
1 error generated.
gmake: *** [Makefile:98: build/release/source/fitz/error.o] Error 1

**Comment by JorjMcKie** [comment]
PyMuPDF does not support MuPDF v1.15 yet

**Comment by JorjMcKie** [comment]
You need to wait until I have found the time for adjusting PyMuPDF.
This will be a major effort unfortunately.
